### PR TITLE
The data Set is ready

### PR DESCRIPTION
**Pull request by LeonPu**
The dataSet used for training

### CODE REVIEW

**Comment by LeonPu** [comment]
I am siyang, and this is the account I am using for github.
There should three files for the dataSet.
CompleteData.mat
ReadMe.docx
sorting.m

**Comment by koosha** [comment]
The commit is not acceptable: 
1) input dataset should be in csv format
2) there shouldn't be any docx in the repo. You can move the content to the readme file or a txt file
3) I was expecting a code in Python as we discussed in our meetings

**Comment by koosha** [comment]
Please put all data files in one folder "data" and commit (data should be in csv format)

**Comment by LeonPu** [comment]
Pull request sent. Please let me know if there is any problem

**Comment by koosha** [comment]
Please remove all html files. You need to upload ipython notebook files (ipynb format) not html

**Comment by LeonPu** [comment]
Fixed some bugs.Accuracy improved.
SVR method is also tried for some bust stops and it performed well. Not committed this time.
Will fix stop19 and 21 later.

**Pull request merged**
